# Form implementation generated from reading ui file 'UI/untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1225, 717)
        MainWindow.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"     background: 3px solid rgb(30, 255, 0);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"QProgressBar {\n"
"        border-radius:10px;\n"
"        background-color: rgba(33, 37, 43, 0);\n"
"        color: black;\n"
"}\n"
"QProgressBar::chunk {\n"
"        background-color: color: rgb(0, 144, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Ust = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ust.sizePolicy().hasHeightForWidth())
        self.Ust.setSizePolicy(sizePolicy)
        self.Ust.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Ust.setObjectName("Ust")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Ust)
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BTN_Ayar = QtWidgets.QPushButton(parent=self.Ust)
        self.BTN_Ayar.setMinimumSize(QtCore.QSize(30, 30))
        self.BTN_Ayar.setMaximumSize(QtCore.QSize(30, 30))
        self.BTN_Ayar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.BTN_Ayar.setStyleSheet("QPushButton{\n"
"     border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgba(255, 255, 255, 30);\n"
"}")
        self.BTN_Ayar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI/Icons/settings.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BTN_Ayar.setIcon(icon)
        self.BTN_Ayar.setObjectName("BTN_Ayar")
        self.horizontalLayout_2.addWidget(self.BTN_Ayar)
        self.widget_2 = QtWidgets.QWidget(parent=self.Ust)
        self.widget_2.setMinimumSize(QtCore.QSize(30, 0))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.BTN_Geri = QtWidgets.QPushButton(parent=self.widget_2)
        self.BTN_Geri.setMinimumSize(QtCore.QSize(30, 30))
        self.BTN_Geri.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.BTN_Geri.setStyleSheet("QPushButton{\n"
"     border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgba(255, 255, 255, 30);\n"
"}")
        self.BTN_Geri.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UI/Icons/chevron-left.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BTN_Geri.setIcon(icon1)
        self.BTN_Geri.setIconSize(QtCore.QSize(20, 20))
        self.BTN_Geri.setObjectName("BTN_Geri")
        self.horizontalLayout_7.addWidget(self.BTN_Geri)
        self.BTN_Ileri = QtWidgets.QPushButton(parent=self.widget_2)
        self.BTN_Ileri.setMinimumSize(QtCore.QSize(30, 30))
        self.BTN_Ileri.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.BTN_Ileri.setStyleSheet("QPushButton{\n"
"     border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgba(255, 255, 255, 30);\n"
"}")
        self.BTN_Ileri.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("UI/Icons/chevron-right.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BTN_Ileri.setIcon(icon2)
        self.BTN_Ileri.setIconSize(QtCore.QSize(20, 20))
        self.BTN_Ileri.setObjectName("BTN_Ileri")
        self.horizontalLayout_7.addWidget(self.BTN_Ileri)
        self.horizontalLayout_2.addWidget(self.widget_2, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget = QtWidgets.QWidget(parent=self.Ust)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 30))
        self.widget.setStyleSheet("background-color: rgb(67, 67, 68);\n"
"border-radius:10px;")
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.BTN_Ara = QtWidgets.QPushButton(parent=self.widget)
        self.BTN_Ara.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.BTN_Ara.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("UI/Icons/search.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BTN_Ara.setIcon(icon3)
        self.BTN_Ara.setObjectName("BTN_Ara")
        self.horizontalLayout_6.addWidget(self.BTN_Ara)
        self.AramaAlan = QtWidgets.QLineEdit(parent=self.widget)
        self.AramaAlan.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.AramaAlan.setObjectName("AramaAlan")
        self.horizontalLayout_6.addWidget(self.AramaAlan)
        self.BTN_Ana = QtWidgets.QPushButton(parent=self.widget)
        self.BTN_Ana.setMinimumSize(QtCore.QSize(30, 30))
        self.BTN_Ana.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.BTN_Ana.setStyleSheet("QPushButton{\n"
"     border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgba(255, 255, 255, 30);\n"
"}")
        self.BTN_Ana.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("UI/Icons/home.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BTN_Ana.setIcon(icon4)
        self.BTN_Ana.setObjectName("BTN_Ana")
        self.horizontalLayout_6.addWidget(self.BTN_Ana)
        self.BTN_Yenile = QtWidgets.QPushButton(parent=self.widget)
        self.BTN_Yenile.setMinimumSize(QtCore.QSize(30, 30))
        self.BTN_Yenile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.BTN_Yenile.setStyleSheet("QPushButton{\n"
"     border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgba(255, 255, 255, 30);\n"
"}")
        self.BTN_Yenile.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("UI/Icons/refresh-cw.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BTN_Yenile.setIcon(icon5)
        self.BTN_Yenile.setObjectName("BTN_Yenile")
        self.horizontalLayout_6.addWidget(self.BTN_Yenile)
        self.horizontalLayout_2.addWidget(self.widget)
        self.BTN_Kontrol = QtWidgets.QPushButton(parent=self.Ust)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_Kontrol.sizePolicy().hasHeightForWidth())
        self.BTN_Kontrol.setSizePolicy(sizePolicy)
        self.BTN_Kontrol.setMinimumSize(QtCore.QSize(30, 30))
        self.BTN_Kontrol.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.BTN_Kontrol.setFont(font)
        self.BTN_Kontrol.setStyleSheet("QPushButton{\n"
"     border-radius:5px;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgba(255, 255, 255, 30);\n"
"}")
        self.BTN_Kontrol.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("UI/Icons/shield.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BTN_Kontrol.setIcon(icon6)
        self.BTN_Kontrol.setIconSize(QtCore.QSize(20, 20))
        self.BTN_Kontrol.setObjectName("BTN_Kontrol")
        self.horizontalLayout_2.addWidget(self.BTN_Kontrol, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addWidget(self.Ust)
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 3))
        self.progressBar.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.MesajWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.MesajWidget.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.MesajWidget.setObjectName("MesajWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.MesajWidget)
        self.horizontalLayout_11.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.MesajText = QtWidgets.QLabel(parent=self.MesajWidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.MesajText.setFont(font)
        self.MesajText.setStyleSheet("color: rgb(0, 0, 0);")
        self.MesajText.setText("")
        self.MesajText.setScaledContents(True)
        self.MesajText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MesajText.setObjectName("MesajText")
        self.horizontalLayout_11.addWidget(self.MesajText, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.BTN_MesajKapat = QtWidgets.QPushButton(parent=self.MesajWidget)
        self.BTN_MesajKapat.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.BTN_MesajKapat.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.BTN_MesajKapat.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("UI/Icons/x_dark.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BTN_MesajKapat.setIcon(icon7)
        self.BTN_MesajKapat.setIconSize(QtCore.QSize(20, 20))
        self.BTN_MesajKapat.setObjectName("BTN_MesajKapat")
        self.horizontalLayout_11.addWidget(self.BTN_MesajKapat, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout.addWidget(self.MesajWidget)
        self.Orta = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Orta.sizePolicy().hasHeightForWidth())
        self.Orta.setSizePolicy(sizePolicy)
        self.Orta.setObjectName("Orta")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Orta)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AyarAlan = QtWidgets.QWidget(parent=self.Orta)
        self.AyarAlan.setMaximumSize(QtCore.QSize(250, 16777215))
        self.AyarAlan.setStyleSheet("background-color: rgb(10,10,10);")
        self.AyarAlan.setObjectName("AyarAlan")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.AyarAlan)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.AyarAlanUst = QtWidgets.QWidget(parent=self.AyarAlan)
        self.AyarAlanUst.setStyleSheet("")
        self.AyarAlanUst.setObjectName("AyarAlanUst")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.AyarAlanUst)
        self.horizontalLayout_5.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(parent=self.AyarAlanUst)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.AyarAlanUst, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.AyarAlanOrta = QtWidgets.QWidget(parent=self.AyarAlan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AyarAlanOrta.sizePolicy().hasHeightForWidth())
        self.AyarAlanOrta.setSizePolicy(sizePolicy)
        self.AyarAlanOrta.setObjectName("AyarAlanOrta")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.AyarAlanOrta)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_10 = QtWidgets.QWidget(parent=self.AyarAlanOrta)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_14.setContentsMargins(-1, -1, 5, 0)
        self.horizontalLayout_14.setSpacing(5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_14.addWidget(self.label_7)
        self.BTN_Engelle = QtWidgets.QPushButton(parent=self.widget_10)
        self.BTN_Engelle.setMinimumSize(QtCore.QSize(61, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.BTN_Engelle.setFont(font)
        self.BTN_Engelle.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 30px;\n"
"    border-radius: 5px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QPushButton:checked {\n"
"     background: 2px solid rgb(30, 255, 0);\n"
"    border: 2px solid rgb(52, 59, 72);    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.BTN_Engelle.setCheckable(True)
        self.BTN_Engelle.setObjectName("BTN_Engelle")
        self.horizontalLayout_14.addWidget(self.BTN_Engelle)
        self.BTN_Sansurle = QtWidgets.QPushButton(parent=self.widget_10)
        self.BTN_Sansurle.setMinimumSize(QtCore.QSize(61, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.BTN_Sansurle.setFont(font)
        self.BTN_Sansurle.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 30px;\n"
"    border-radius: 5px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QPushButton:checked {\n"
"     background: 2px solid rgb(30, 255, 0);\n"
"    border: 2px solid rgb(52, 59, 72);    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.BTN_Sansurle.setCheckable(True)
        self.BTN_Sansurle.setChecked(True)
        self.BTN_Sansurle.setObjectName("BTN_Sansurle")
        self.horizontalLayout_14.addWidget(self.BTN_Sansurle)
        self.verticalLayout_4.addWidget(self.widget_10)
        self.widget_5 = QtWidgets.QWidget(parent=self.AyarAlanOrta)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_10.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setWhatsThis("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.CB_OtomatikKontrol = QtWidgets.QCheckBox(parent=self.widget_5)
        self.CB_OtomatikKontrol.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.CB_OtomatikKontrol.setStyleSheet("")
        self.CB_OtomatikKontrol.setText("")
        self.CB_OtomatikKontrol.setChecked(True)
        self.CB_OtomatikKontrol.setObjectName("CB_OtomatikKontrol")
        self.horizontalLayout_10.addWidget(self.CB_OtomatikKontrol)
        self.verticalLayout_4.addWidget(self.widget_5, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.line_2 = QtWidgets.QFrame(parent=self.AyarAlanOrta)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.line_3 = QtWidgets.QFrame(parent=self.AyarAlanOrta)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.widget_7 = QtWidgets.QWidget(parent=self.AyarAlanOrta)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_6.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.CB_Tema = QtWidgets.QCheckBox(parent=self.widget_7)
        self.CB_Tema.setEnabled(False)
        self.CB_Tema.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.CB_Tema.setText("")
        self.CB_Tema.setObjectName("CB_Tema")
        self.horizontalLayout_8.addWidget(self.CB_Tema)
        self.verticalLayout_4.addWidget(self.widget_7, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_3.addWidget(self.AyarAlanOrta, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.line_4 = QtWidgets.QFrame(parent=self.AyarAlan)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.AyarTexts = QtWidgets.QWidget(parent=self.AyarAlan)
        self.AyarTexts.setObjectName("AyarTexts")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.AyarTexts)
        self.verticalLayout_7.setContentsMargins(-1, 0, 12, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_3.addWidget(self.AyarTexts)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.widget_11 = QtWidgets.QWidget(parent=self.AyarAlan)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.verticalLayout_3.addWidget(self.widget_11)
        self.IndirmeText = QtWidgets.QLabel(parent=self.AyarAlan)
        self.IndirmeText.setText("")
        self.IndirmeText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.IndirmeText.setObjectName("IndirmeText")
        self.verticalLayout_3.addWidget(self.IndirmeText)
        self.IndirmeBar = QtWidgets.QProgressBar(parent=self.AyarAlan)
        self.IndirmeBar.setProperty("value", 0)
        self.IndirmeBar.setObjectName("IndirmeBar")
        self.verticalLayout_3.addWidget(self.IndirmeBar)
        self.widget_8 = QtWidgets.QWidget(parent=self.AyarAlan)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_3.addWidget(self.widget_8)
        self.horizontalLayout.addWidget(self.AyarAlan)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.Orta)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.WebAlan = QtWidgets.QWidget()
        self.WebAlan.setObjectName("WebAlan")
        self.stackedWidget.addWidget(self.WebAlan)
        self.Page = QtWidgets.QWidget()
        self.Page.setObjectName("Page")
        self.stackedWidget.addWidget(self.Page)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.RaporAlan = QtWidgets.QWidget(parent=self.Orta)
        self.RaporAlan.setMaximumSize(QtCore.QSize(300, 16777215))
        self.RaporAlan.setStyleSheet("background-color: rgb(10,10,10);background-color: rgb(16, 16, 16);")
        self.RaporAlan.setObjectName("RaporAlan")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.RaporAlan)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.RaporAlanUst = QtWidgets.QWidget(parent=self.RaporAlan)
        self.RaporAlanUst.setStyleSheet("")
        self.RaporAlanUst.setObjectName("RaporAlanUst")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.RaporAlanUst)
        self.horizontalLayout_4.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.RaporAlanUst)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.verticalLayout_2.addWidget(self.RaporAlanUst)
        self.widget_4 = QtWidgets.QWidget(parent=self.RaporAlan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_6.setSpacing(20)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setStyleSheet("background-color: rgb(67, 67, 68);\n"
"border-radius:10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.textEdit = QtWidgets.QTextEdit(parent=self.widget_3)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 250))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 250))
        self.textEdit.setStyleSheet("background-color: rgb(67, 67, 68);\n"
"border-radius:10px;")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_5.addWidget(self.textEdit)
        self.verticalLayout_6.addWidget(self.widget_3, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.checkBox = QtWidgets.QCheckBox(parent=self.widget_4)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_6.addWidget(self.checkBox)
        self.CB_Rapor = QtWidgets.QCheckBox(parent=self.widget_4)
        self.CB_Rapor.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.CB_Rapor.setObjectName("CB_Rapor")
        self.verticalLayout_6.addWidget(self.CB_Rapor)
        self.BTN_RaporGonder = QtWidgets.QPushButton(parent=self.widget_4)
        self.BTN_RaporGonder.setEnabled(False)
        self.BTN_RaporGonder.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.BTN_RaporGonder.setFont(font)
        self.BTN_RaporGonder.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.BTN_RaporGonder.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 30px;\n"
"    border-radius: 5px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QPushButton:pressed {\n"
"     background: 2px solid rgb(30, 255, 0);\n"
"    border: 2px solid rgb(52, 59, 72);    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:checked {\n"
"     background: 2px solid rgb(30, 255, 0);\n"
"    border: 2px solid rgb(52, 59, 72);    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.BTN_RaporGonder.setCheckable(True)
        self.BTN_RaporGonder.setChecked(False)
        self.BTN_RaporGonder.setObjectName("BTN_RaporGonder")
        self.verticalLayout_6.addWidget(self.BTN_RaporGonder)
        self.RaporYazi = QtWidgets.QLabel(parent=self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        self.RaporYazi.setFont(font)
        self.RaporYazi.setStyleSheet("color: rgb(255, 45, 0);")
        self.RaporYazi.setText("")
        self.RaporYazi.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.RaporYazi.setObjectName("RaporYazi")
        self.verticalLayout_6.addWidget(self.RaporYazi, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.horizontalLayout.addWidget(self.RaporAlan)
        self.verticalLayout.addWidget(self.Orta)
        self.Alt = QtWidgets.QWidget(parent=self.centralwidget)
        self.Alt.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Alt.setObjectName("Alt")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Alt)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 5)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BTN_Rapor = QtWidgets.QPushButton(parent=self.Alt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_Rapor.sizePolicy().hasHeightForWidth())
        self.BTN_Rapor.setSizePolicy(sizePolicy)
        self.BTN_Rapor.setMinimumSize(QtCore.QSize(77, 25))
        self.BTN_Rapor.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.BTN_Rapor.setWhatsThis("")
        self.BTN_Rapor.setStyleSheet("QPushButton{\n"
"     border-radius:5px;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgba(255, 255, 255, 30);\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("UI/Icons/flag.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BTN_Rapor.setIcon(icon8)
        self.BTN_Rapor.setObjectName("BTN_Rapor")
        self.horizontalLayout_3.addWidget(self.BTN_Rapor, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout.addWidget(self.Alt)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AramaAlan.setPlaceholderText(_translate("MainWindow", "Arama Yapabilirsiniz..."))
        self.label_2.setText(_translate("MainWindow", "Genel Ayarlar"))
        self.label_7.setText(_translate("MainWindow", "Riskli Sayfalar"))
        self.BTN_Engelle.setText(_translate("MainWindow", "Engelle"))
        self.BTN_Sansurle.setText(_translate("MainWindow", "Sansürle"))
        self.label_4.setStatusTip(_translate("MainWindow", "hahahahhahaha"))
        self.label_4.setText(_translate("MainWindow", "Otomatik Kontrol"))
        self.label_6.setText(_translate("MainWindow", "Açık Tema"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">SHIFT + J </span> = Hızlı Kontrol</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">CTRL + P</span>   = Ekran Görüntüsü</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Zorbalık Raporla"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Başlığı Buraya Yazabilirsiniz.."))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Mesajınızı Buraya Yazabilirsiniz..."))
        self.checkBox.setText(_translate("MainWindow", " Ekran Görüntüsü Ekle"))
        self.CB_Rapor.setText(_translate("MainWindow", " Tüm Şartları ve Koşulları Kabul Ediyorum"))
        self.BTN_RaporGonder.setText(_translate("MainWindow", "Gönder"))
        self.BTN_Rapor.setText(_translate("MainWindow", "Raporla"))
